name: Release
on:
  push:
    branches:
      - ci-testing
permissions:
  id-token: write
jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
          # Pull all previous tags
          fetch-depth: 0
          fetch-tags: true
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@spaceandtime'

      - name: Bun install
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH


      - name: Publish to npm
        working-directory: ./packages/cre-sdk-javy-plugin
        run: |
          npm publish --access public --non-interactive

      - name: Publish to npm
        working-directory: packages/cre-sdk
        run: |
          npm publish --access public --non-interactive